### ISSUE TITLE
Improvement: Allow Changing of Colour

### ISSUE THREAD

**Issue by Blumlaut** [SWRP-PUBLIC/pogressBar#2]
Instead of it being defined in 
https://github.com/SWRP-PUBLIC/pogressBar/blob/master/html/style.css#L39

it would be neat being able to select a custom colour, something like this maybe?

```
TriggerEvent('pogressBar:drawBar', 3000, 'Hello world!', {255,255,255,100})
```

maybe even allowing the whole css to be edited on the fly, would be even cooler.

**Comment by Poggicek** [comment]
Yeah i can make something like that.

**Comment by Poggicek** [comment]
I will add parameter for options where you would be able to change the color or the whole css. Then i could add more things in options

**Comment by Poggicek** [comment]
Aight i got a working prototype, it looks like this ```
drawBar(500, 'fdsfs', function()
		print('callback Test')
	end, {
		color = 'blue',
		customCSS = {
			maxWidth = "5px"
		}
	})```

**Comment by Poggicek** [comment]
![image](https://user-images.githubusercontent.com/45881722/67634726-fdae2080-f8bf-11e9-9ed0-d734f0f17e54.png)
This is the end result

**Comment by Poggicek** [comment]
Thanks for your suggestion, it was added to the script
